### ISSUE TITLE
Add website link in repository metadata

### ISSUE THREAD

**Issue by Pustur** [Roblouisck/mysaves.app#5]
Can you add the website URL in the field near the description?

<img width="995" alt="Screenshot 2019-08-19 at 03 09 55" src="https://user-images.githubusercontent.com/13663338/63233187-ec48f800-c22e-11e9-9fa3-952e1e56d010.png">

Just for convenience, I know it's already in the readme.

Thanks.

**Comment by Roblouisck** [comment]
Done 👍
