### ISSUE TITLE
[Feature request] View saves by subreddit

### ISSUE THREAD

**Issue by ThinkSalat** [Roblouisck/mysaves.app#6]
It'd be cool to view your saved content by subreddit. What I envision is a list of subredddits you have saved stuff from, with the count of the number of saved articles in that subreddit. Then you can select whichever ones you want. 

I can help if you want to slack or talk about how to achieve this!

**Comment by Roblouisck** [comment]
Hey ThinkSalat,

Thanks for the suggestion. This type of feature is something I considered early in development, but decided that the filter system was sufficient. We can already filter by subreddits, so the utility this feature would bring is being able to see all your subreddits at a glance. 

When I built the app I decided to group subreddits together on the threads only page automatically to include this utility of being able to see all your different subreddits quickly without adding additional complexity. Therefore, I don't see enough upside in this feature idea to warrant disruption of the current design. 

Will close the feature request for now, thank you for the suggestion.
