### ISSUE TITLE
Creating an environment variable file to store uri and client id

### ISSUE THREAD

**Issue by FlashBlaze** [Roblouisck/mysaves.app#9]
Instead of replacing the variables in `Render.js`, it would be efficient to create a `.env.development` file to store the variables in.
I would be happy to submit a PR with necessary changes in `README.md`

**Comment by Roblouisck** [comment]
Hey FlashBlaze, I made some comments on your PR. Follow the comments and I'll be happy to update the readme with your suggestion.
